import Head from 'next/head';
import { NextPage } from 'next';
import Header from '@/components/Header';
// import Basket from '@/components/Basket';
import Landing from '@/components/Landing';
import Tabs from '@/components/Tabs';
import { useQuery } from '@apollo/client';
import { CATEGORIES } from '@/queries';

const ProtectedPost: NextPage = (): JSX.Element => {
  const { data, loading, error } = useQuery(CATEGORIES, {
    variables: {
      amount: 4,
    },
  });
  return (
    <>
      <Head>
        <title>Apple</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/apple.ico' />
      </Head>
      <Header />
      {/* <Basket /> */}
      <main className='relative h-[200vh] bg-background'>
        <Landing />
      </main>
      <section className='relative z-40 -mt-[100vh] min-h-screen bg-darkBackground'>
        <div className='space-y-10 py-16'>
          <h1 className='text-center text-4xl font-medium tracking-wide text-white'>
            New Promos
          </h1>
          {data && (
            <Tabs
              categories={data.getCategories}
              firstCategory={data.getCategories[0]._id}
            />
          )}
        </div>
      </section>
    </>
  );
};

export default ProtectedPost;
